package proxy

import (
	"net/http"
	"testing"
)

func TestComputeJCSHash(t *testing.T) {
	tests := []struct {
		name  string
		value interface{}
	}{
		{"string", "hello"},
		{"number", float64(42)},
		{"boolean", true},
		{"null", nil},
		{"object", map[string]interface{}{"b": 2, "a": 1}},
		{"nested", map[string]interface{}{"user": map[string]interface{}{"name": "Chris"}, "body": "Hello!"}},
		{"array", []interface{}{1, 2, 3}},
		{"empty object", map[string]interface{}{}},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			hash, err := computeJCSHash(tt.value)
			if err != nil {
				t.Fatalf("computeJCSHash() error: %v", err)
			}

			// Hash should be 64 hex chars (SHA-256)
			if len(hash) != 64 {
				t.Errorf("hash length = %d, want 64", len(hash))
			}

			// Should be deterministic
			hash2, err := computeJCSHash(tt.value)
			if err != nil {
				t.Fatalf("computeJCSHash() second call error: %v", err)
			}
			if hash != hash2 {
				t.Errorf("hash not deterministic: %q != %q", hash, hash2)
			}
		})
	}
}

// TestComputeJCSHashKnownValues verifies exact hash output against lark-server's implementation.
// These values were generated by the same JCS+SHA-256 pipeline to catch cross-implementation drift.
func TestComputeJCSHashKnownValues(t *testing.T) {
	tests := []struct {
		name  string
		value interface{}
		want  string
	}{
		{
			name:  "string hello",
			value: "hello",
			want:  "5aa762ae383fbb727af3c7a36d4940a5b8c40a989452d2304fc958ff3f354e7a",
		},
		{
			name:  "number 42",
			value: float64(42),
			want:  "73475cb40a568e8da8a045ced110137e159f890ac4da883b6b17dc651b3a8049",
		},
		{
			name:  "boolean true",
			value: true,
			want:  "b5bea41b6c623f7c09f1bf24dcae58ebab3c0cdd90ad966bc43a45b44867e12b",
		},
		{
			name:  "null",
			value: nil,
			want:  "74234e98afe7498fb5daf1f36ac2d78acc339464f950703b8c019892f982b90b",
		},
		{
			name:  "object sorted keys",
			value: map[string]interface{}{"a": float64(1), "b": float64(2)},
			want:  "43258cff783fe7036d8a43033f830adfc60ec037382473548ac742b888292777",
		},
		{
			name:  "object unsorted keys (same hash)",
			value: map[string]interface{}{"b": float64(2), "a": float64(1)},
			want:  "43258cff783fe7036d8a43033f830adfc60ec037382473548ac742b888292777",
		},
		{
			name:  "nested object",
			value: map[string]interface{}{"user": map[string]interface{}{"name": "Chris"}, "body": "Hello!"},
			want:  "badd0fcc6588635fdd67082e026dea42a2d5848381ee7d52a95ed65c276f61c4",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := computeJCSHash(tt.value)
			if err != nil {
				t.Fatalf("computeJCSHash() error: %v", err)
			}
			if got != tt.want {
				t.Errorf("computeJCSHash() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestComputeJCSHashCanonicalOrdering(t *testing.T) {
	// JCS sorts keys lexicographically, so these should produce the same hash
	v1 := map[string]interface{}{"b": 2, "a": 1, "c": 3}
	v2 := map[string]interface{}{"c": 3, "a": 1, "b": 2}

	h1, err := computeJCSHash(v1)
	if err != nil {
		t.Fatal(err)
	}
	h2, err := computeJCSHash(v2)
	if err != nil {
		t.Fatal(err)
	}
	if h1 != h2 {
		t.Errorf("different key order produced different hashes: %q != %q", h1, h2)
	}
}

func TestComputeJCSHashDifferentValues(t *testing.T) {
	h1, _ := computeJCSHash("hello")
	h2, _ := computeJCSHash("world")
	if h1 == h2 {
		t.Error("different values produced same hash")
	}
}

func TestMapLarkErrorToHTTP(t *testing.T) {
	tests := []struct {
		errorCode string
		want      int
	}{
		{"permission_denied", http.StatusForbidden},
		{"unauthenticated", http.StatusUnauthorized},
		{"invalid_data", http.StatusBadRequest},
		{"invalid_token", http.StatusBadRequest},
		{"not_found", http.StatusNotFound},
		{"unavailable", http.StatusServiceUnavailable},
		{"condition_failed", http.StatusPreconditionFailed},
		{"unknown_error", http.StatusInternalServerError},
	}

	for _, tt := range tests {
		t.Run(tt.errorCode, func(t *testing.T) {
			got := mapLarkErrorToHTTP(tt.errorCode)
			if got != tt.want {
				t.Errorf("mapLarkErrorToHTTP(%q) = %d, want %d", tt.errorCode, got, tt.want)
			}
		})
	}
}
